### ISSUE TITLE
[Question] Is it possible to upload multiple files

### ISSUE THREAD

**Issue by xetra11** [sinshutu/upload-to-discord#10]
The `args` property sounds plural. I wonder if it is possible to upload multiple files or do I have to make a step for each file?

**Comment by sinshutu** [comment]
@xetra11 it is possible.
see https://github.com/sinshutu/upload-to-discord/blob/master/.github/workflows/main.yml

**Comment by sinshutu** [comment]
@xetra11 Close issue, but if not resolved please reopen
