### ISSUE TITLE
How to add text to args: to ping role

### ISSUE THREAD

**Issue by dG9hc3Q** [sinshutu/upload-to-discord#8]
For example I want it ping a certain roles with every upload.

**Comment by sinshutu** [comment]
Wouldn't it be better to add such an Action?
What is the necessity of doing it in discord-to-upload action?

**Comment by dG9hc3Q** [comment]
I just want it to automatically ping a role everytime an upload happens is this possible currently?

**Comment by sinshutu** [comment]
It's impossible to do in this action.

**Comment by dG9hc3Q** [comment]
Another dev figured out a way if you wanna know how ask him wnuke#1010
